// <auto-generated />
using System;
using Exam.App.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Exam.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Exam.App.Domain.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Exam.App.Domain.Models.AnimalSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CageId")
                        .HasColumnType("integer");

                    b.Property<double?>("Mass")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CageId");

                    b.ToTable("AnimalSpecies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CageId = 1,
                            Mass = 190.0,
                            Name = "Lav",
                            Species = "Panthera leo"
                        },
                        new
                        {
                            Id = 2,
                            CageId = 2,
                            Mass = 220.0,
                            Name = "Tigar",
                            Species = "Panthera tigris"
                        },
                        new
                        {
                            Id = 3,
                            CageId = 3,
                            Mass = 6000.0,
                            Name = "Slon",
                            Species = "Loxodonta africana"
                        },
                        new
                        {
                            Id = 4,
                            CageId = 3,
                            Mass = 800.0,
                            Name = "Žirafa",
                            Species = "Giraffa camelopardalis"
                        },
                        new
                        {
                            Id = 5,
                            CageId = 1,
                            Mass = 350.0,
                            Name = "Zebra",
                            Species = "Equus quagga"
                        },
                        new
                        {
                            Id = 6,
                            CageId = 3,
                            Mass = 2300.0,
                            Name = "Nosorog",
                            Species = "Rhinocerotidae"
                        },
                        new
                        {
                            Id = 7,
                            CageId = 2,
                            Mass = 72.0,
                            Name = "Gepard",
                            Species = "Acinonyx jubatus"
                        },
                        new
                        {
                            Id = 8,
                            CageId = 2,
                            Mass = 60.0,
                            Name = "Hijena",
                            Species = "Crocuta crocuta"
                        },
                        new
                        {
                            Id = 9,
                            CageId = 3,
                            Mass = 300.0,
                            Name = "Medved",
                            Species = "Ursus arctos"
                        },
                        new
                        {
                            Id = 10,
                            CageId = 7,
                            Mass = 50.0,
                            Name = "Vuk",
                            Species = "Canis lupus"
                        },
                        new
                        {
                            Id = 11,
                            CageId = 7,
                            Mass = 8.0,
                            Name = "Lisica",
                            Species = "Vulpes vulpes"
                        },
                        new
                        {
                            Id = 12,
                            CageId = 4,
                            Mass = 1.2,
                            Name = "Sova",
                            Species = "Strix aluco"
                        },
                        new
                        {
                            Id = 13,
                            CageId = 4,
                            Mass = 6.0,
                            Name = "Orao",
                            Species = "Aquila chrysaetos"
                        },
                        new
                        {
                            Id = 14,
                            CageId = 5,
                            Mass = 500.0,
                            Name = "Krokodil",
                            Species = "Crocodylus niloticus"
                        },
                        new
                        {
                            Id = 15,
                            CageId = 6,
                            Mass = 30.0,
                            Name = "Pingvin",
                            Species = "Aptenodytes forsteri"
                        },
                        new
                        {
                            Id = 16,
                            CageId = 4,
                            Mass = 3.0,
                            Name = "Flamingo",
                            Species = "Phoenicopterus roseus"
                        },
                        new
                        {
                            Id = 17,
                            CageId = 1,
                            Mass = 85.0,
                            Name = "Kengur",
                            Species = "Macropus rufus"
                        },
                        new
                        {
                            Id = 18,
                            CageId = 3,
                            Mass = 100.0,
                            Name = "Panda",
                            Species = "Ailuropoda melanoleuca"
                        },
                        new
                        {
                            Id = 19,
                            CageId = 7,
                            Mass = 3.0,
                            Name = "Lemur",
                            Species = "Lemur catta"
                        },
                        new
                        {
                            Id = 20,
                            CageId = 6,
                            Mass = 200.0,
                            Name = "Morski lav",
                            Species = "Zalophus californianus"
                        });
                });

            modelBuilder.Entity("Exam.App.Domain.Models.Cage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "A1-SAVANA"
                        },
                        new
                        {
                            Id = 2,
                            Code = "A2-DŽUNGLA"
                        },
                        new
                        {
                            Id = 3,
                            Code = "A3-PLANINA"
                        },
                        new
                        {
                            Id = 4,
                            Code = "B1-PTICE"
                        },
                        new
                        {
                            Id = 5,
                            Code = "B2-REPTILI"
                        },
                        new
                        {
                            Id = 6,
                            Code = "C1-VODENI"
                        },
                        new
                        {
                            Id = 7,
                            Code = "C2-NOĆNI"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Exam.App.Domain.Models.AnimalSpecies", b =>
                {
                    b.HasOne("Exam.App.Domain.Models.Cage", "Cage")
                        .WithMany("CagedAnimals")
                        .HasForeignKey("CageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cage");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Exam.App.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Exam.App.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.App.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Exam.App.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.App.Domain.Models.Cage", b =>
                {
                    b.Navigation("CagedAnimals");
                });
#pragma warning restore 612, 618
        }
    }
}
